### ISSUE TITLE
[AOS] 일정 추정 및 계획 수립

### ISSUE THREAD

**Issue by MgNuu** [softeerbootcamp-3rd/Team7-FiveGuys#5]
## ✏️ 작업 설명
> AOS 작업 계획 수립
<br/>

## 📝 작업 목록
- [x] UI 구현 역할 분담
- 민우
>목적지 설정 페이지
택시 대기 / 탑승 후 출발 페이지 (실시간 내비게이션)
차량제어 뷰 (슬라이딩 패널)
결제 페이지 (결제 sdk 사용)

- 상민
>로그인 페이지
메인 페이지
동승 요청 푸시알림 (실시간 푸시알림)
동승 가능 차량 리스트 선택 페이지 (리사이클러뷰)
후기 페이지

- 용호
>회원가입 페이지
내 정보 페이지
>1. 회원정보 수정 페이지
>2. 비밀번호 수정 페이지 

- [x] 일정 예상
<br/>

## ⏰ 예상 소요 시간
> 2/6 (화) 19:00까지
<br/>

## 참고사항 (선택)
> 디자인 분담 및 일정 -> https://www.figma.com/file/Q38jwZ94YfF0ZEman14z7X/7%EC%A1%B0-%EB%AA%A9%EC%97%85?type=design&node-id=317%3A11177&mode=design&t=R4b4Wy2gAXo2F9cP-1

**Comment by lsh2613** [comment]
to do list를 종합해서 올리는 것보단 각자 해야할 일들을 task로 만들어서 올리면 더 좋을 것 같아요~!
