### ISSUE TITLE
[BE] 서버에서 외부 api사용할때 resttemplate을 사용하는것보다 나은게 있을까요?

### ISSUE THREAD

**Issue by yo0919** [softeerbootcamp-3rd/Team7-FiveGuys#65]
# 서버에서 외부 api사용할때 resttemplate을 사용하는것보다 나은게 있을까요?

> 백엔드에서 외부api(네이버맵,토스)등을 호출할때 resttemplate을 사용하였는데, 
그이유는 Spring 3.0부터 지원되었고, json, xml 응답을 모두 받을 수 있으며 Rest API 서비스를 요청 후 응답 받을 수 있도록 설계되어있어서 HTTP 프로토콜의 메소드(ex. GET, POST, DELETE, PUT)들에 적합한 여러 메소드들을 제공하기 때문이었습니다.      

> 그런데 Spring Framework 5부터는 WebFlux 스택과 함께 Spring은 WebClient 라는 새로운 HTTP 클라이언트를 도입하여 기존의 동기식 API를 제공할 뿐 만 아니라 효율적인 비차단 및 비동기 접근 방식을 지원하여, Spring 5.0 이후 부터는 RestTemplate는 deprecated 되었다고 하네요.

## 찾아본내용
기존에 사용하던 Resttemplate의 동작원리는 다음과 같습니다.

1. 애플리케이션 내부에서 REST API에 요청하기 위해 RestTemplate의 메서드를 호출한다.
2. RestTemplate은 MessageConverter를 이용해 java object를 request body에 담을 message(JSON etc.)로 변환한다. 메시지 형태는 상황에 따라 다름
3. ClientHttpRequestFactory에서 ClientHttpRequest을 받아와 요청을 전달한다.
4. 실질적으로 ClientHttpRequest가 HTTP 통신으로 요청을 수행한다.
5. RestTemplate이 에러핸들링을 한다.
6. ClientHttpResponse에서 응답 데이터를 가져와 오류가 있으면 처리한다.
7. MessageConverter를 이용해 response body의 message를 java object로 변환한다.
8. 결과를 애플리케이션에 돌려준다.
![1](https://github.com/softeerbootcamp-3rd/Team7-FiveGuys/assets/104425318/a450a47f-4c20-4f3e-b413-5dff5538756e)

실제 사용은 이렇게 사용하고 있습니다.
```
public MapService(RestTemplate restTemplate, @Value("${naver.api.key.id}") String apiKeyId, @Value("${naver.api.key.secret}") String apiKeySecret) {
        this.restTemplate = restTemplate;
        this.apiKeyId = apiKeyId;
        this.apiKeySecret = apiKeySecret;
    }
```

그런데 기존 resttemplate은 동기적인 방식으로 작동하며, WebClient는 비동기적이고 리액티브한 방식으로 작동한다고 합니다.
실제로 최근에는 resttemplate을 권장하지 않는다고하는데, 저는 간단한 프로젝트이고 동기/비동기성을 고려하여 얻는 이점보다 더 간단하고 쉽게 요청을 보내는 장점이 좀더 크다고 생각하여 resttemplate을 사용하긴 했었습니다. 

## 결론 Resttemplate vs Webclient
> 이러한 장단점을 고려하여 둘중 무엇을 선택하는게 좋을지 물어보고자 합니다

### 참고사항
> [Resttemplate 관련설명](https://blog.naver.com/hj_kim97/222295259904)
[Resttemplate과 Webclient 차이](https://happycloud-lee.tistory.com/220)

**Comment by lsh2613** [comment]
저도 외부 api를 호출하기 위해 RestTemplate vs WebClient에 대해 찾아봤었는데 비슷한 내용에 이슈가 올라와있었네요
우선 언급하신 내용 중에 틀린 부분을 말씀드리면 Spring 5.0 이후 부터는 RestTemplate는 deprecated되었다고 하는데 사실은 maintenance mode(유지 모드)로 변경되었습니다. 예전에 deprecated될 예정이라고 스프링에서 커밋을 날렸었는데 이후 deprecated되지 않고 maintenance mode가 되었음을 다음 [링크](https://docs.spring.io/spring-framework/reference/6.0-SNAPSHOT/integration/rest-clients.html#rest-resttemplate)에서 확인해볼 수 있습니다. 하단 사진으로도 확인 가능하다.

![Image](https://github.com/softeerbootcamp-3rd/Team7-FiveGuys/assets/104637774/52826126-c1b6-4ace-b839-7d36e1d61e2f)

저는 사진에서 처럼 WebClient를 추천하고 있는데 이유가 뭘까에 대해서 RestTemplate vs WebClient에 대해 먼저 조사를 해봤습니다.

## RestTemplate vs WebClient
가장 큰 차이점은 언급해주셨 듯이 RestTemplate은 동기, WebClient는 비동기 방식이고 추가로 RestTemplate는 blocking을 지원하고 WebClient는 WebFlux 라이브러리로 동기,비동기, blocking, non-blocking을 모두 지원한다는 차이점이 있었습니다.

## 결론
제가 구현하고 있는 API에 경우 외부 api 응답을 반환해줘야 하기 때문에 동기-블로킹을 사용해도 문제가 없다고 판단하였고 spring-boot-starter-web에 RestTemplate이 있어 굳이 WebFlux 의존성을 추가하여 WebClient의 block을 사용할 필요가 없다고 느꼈습니다.

추가로 WebClient로 비동기를 지원한다고 하더라도 해당 부분에서 연관 로직이 동기라면 비동기의 이점을 얻을 수 없다고 하네요.

동기 vs 비동기, 블로킹 vs 논-블로킹에 대한 개념이 상당히 어려워 이부분에 대해서는 추가적으로 같이 학습을 해보면 좋을 것 같습니다!

**Comment by lsh2613** [comment]
추가로 조사해본 결과 스프링 MVC는 논-블로킹 방식이라 스프링 mvc 프로젝트에서 비동기-논블로킹의 webflux라이브러리를 사용하더라도 이 이점을 얻을 수 없다고 하네요. 이 내용에 대해서 새로 이슈를 파서 더 자세하게 다뤄보겠습니다
