### ISSUE TITLE
[BE] 출발,도착지 값으로 최단경로를 받고싶을때 GET, POST메서드 중에서 어떤 메서드가 맞을까요?

### ISSUE THREAD

**Issue by yo0919** [softeerbootcamp-3rd/Team7-FiveGuys#66]
# 출발,도착지 값으로 최단경로를 받고싶을때 GET, POST메서드 중에서 어떤 메서드가 맞을까요?
> OperationController에서 (가제)/operations/optimized-route 라는 api를 만들었는데 출발도착지를 reqbody로 받고 resbody에 필요한 값을 보내주는 POST라고 생각했습니다. 
그런데 동민이형이 만든걸 보니 요청 파라미터들을 /operations/carpools?guestDepartAddress=&guestDestAddress= 이런식으로 보내면서 GET매서드로 처리하는고 있네요. 둘중어떤게 더 적합할지 궁금합니다

## 📝 찾아본내용
- GET을 써야한다 : 최적의 경로 계산은 서버에 어떤 새로운 정보를 "생성"하는 것이 아니라, 주어진 입력값(출발지와 도착지)에 대해 계산된 결과를 "조회"하는 작업에 더 가깝기때문에 GET을 사용하는것이 나을것같다.
- POST를 써야한다 : 복잡한 데이터(예: 좌표, 주소 등)를 요청에 포함해야 하고, 이 데이터를 URL에 담기에는 부적절하거나 비효율적일 수 있기 때문에, 이러한 경우에 POST 메소드를 사용하는 것이 나을것같다.
<br>

## 결론 : GET vs POST
> 저는 개인적으로 이 api가 '직접 데이터베이스에 등록하는 과정이 없기때문에 GET을 써야한다.' 라는것에 대한 의문이 있습니다. 물론 출발,도착지가 보안적으로 중요한 값이 아니라고 하더라도 쿼리스트링이 url에 포함된다는것도 약간의 거부감도 있구요. 여러분은 어떻게 생각하시나요?
<br>

**Comment by eyeben** [comment]
오.. 저도 고민했었던 주제네요 ㅋㅋㅋ

저도 POST가 더 적합하다고 생각하는데요. 그때는 주소 2개를 쿼리 스트링으로 하면 URL이 너무 길어져서 사용하기 꺼려했는데 안드로이드 측과 이야기를 했을 때 쿼리스트링으로 받는 것을 선호하셔서 GET으로 했었어요.

근데 지금 생각해보면 도착지 주소도 민감한 정보라고 볼 수도 있어서 보안에 신경쓰는 것도 나쁘지 않을 것 같네요 :/

**Comment by lsh2613** [comment]
저는 get과 post를 구분할 때 넘어오는 데이터를 가지고 상태를 변경(데이터베이스에 등록, 수정 등)하는지의 여부를 가지고 판단합니다. 단순히 해당 데이터를 가지고 조회만 한다면 GET, 상태를 변경한다면 POST를 사용합니다.

또한 GET 요청은 브라우저에 의해 캐싱될 수 있으며, 브라우저 기록에 남습니다. 반면, POST 요청은 캐싱되지 않으며 브라우저 기록에도 남지 않습니다. 해당 주제에 대해서는 결국 '조회'에 대한 api이 같아 GET을 사용하는 것이 적합해 보입니다.

결론적으로 데이터 조회와 같은 멱등(idempotent)한 작업에는 GET을, 데이터를 생성하거나 변경하는 등의 비멱등(non-idempotent)한 작업에는 POST를 사용하는 것이 바람직한 방법일 것 같습니다

**Comment by yo0919** [comment]
안드로이드 팀원에서도 쿼리스트링 방식을 선호하고, 멱등성의 관점에서 본다면 GET으로 진행하는 편이 맞는것같긴하네요. 출발도착지가 보안상으로 크게 중요한내용이거나, 복잡성이 높은 데이터라고 판단하지 않는다면 그대로 GET으로 진행해도 될것같습니다!
