### ISSUE TITLE
[BE] @RequestMapping의 사용

### ISSUE THREAD

**Issue by yo0919** [softeerbootcamp-3rd/Team7-FiveGuys#68]
## ✏️건의하고 싶은 내용
> @RequestMapping의 사용
<br>

## 📝 찾아본내용
- @RequestMapping 없이 사용할 때 : HTTP 메서드 별로 어노테이션(@GetMapping, @PostMapping, @PutMapping, @DeleteMapping 등)을 사용하여 각 메서드의 용도와 경로를 명시
```
 @PostMapping("/garage") // 이부분
    public ResponseEntity insertGarage(@RequestBody @Validated GarageReqDto garageReqDto,
                                       Errors errors) {
        if (errors.hasErrors()) {
            return ResponseApi.invalidArguments();
        }

        try {
            garageService.insertGarage(garageReqDto);
        } catch (IllegalArgumentException e) {
            return ResponseApi.of(ResponseStatus.GARAGE_ALREADY_EXIST);
        }
        return ResponseApi.ok();
    }
```
@RequestMapping 사용할 때 : 클래스 전체에 적용되는 기본 URL 경로를 지정할 수 있습니다. 이후 클래스 내의 각 메서드는 이 기본 경로에 추가적인 경로를 덧붙여 사용하여 URL 경로에 일관성을 주고, 중복을 줄이게 됩니다.
```
@RestController
@RequiredArgsConstructor
@Tag(name = "Garage", description = "Garage(차고) 도메인 API")
@RequestMapping("/garage") // 클래스 레벨에서 기본 경로를 설정
public class GarageController {

    private final GarageService garageService;

    @Operation(summary = "차고지 추가하기")
    @Parameters(value = {
            @Parameter(name = "latitude", description = "위도"),
            @Parameter(name = "longitude", description = "경도")})
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "추가 성공"),
            @ApiResponse(responseCode = "409", description = "중복된 차고지 위치로 추가")})
    @PostMapping() // 이렇게 수정
    public ResponseEntity insertGarage(@RequestBody @Validated GarageReqDto garageReqDto,
                                       Errors errors) {
        if (errors.hasErrors()) {
            return ResponseApi.invalidArguments();
        }

        try {
            garageService.insertGarage(garageReqDto);
        } catch (IllegalArgumentException e) {
            return ResponseApi.of(ResponseStatus.GARAGE_ALREADY_EXIST);
        }
        return ResponseApi.ok();
    }
}
```
<br>

## 결론
> 이렇게 변경하는게 어떤가 하는 생각이 드는데 어떻게 생각하시나요?
<br>

**Comment by eyeben** [comment]
신기한 기능이네요 
두 방식 모두 장단점이 있어서 취향 차이인거 같은데 저는 찬성입니다

**Comment by lsh2613** [comment]
이 방법도 좋은 방법이라고 생각합니다. 이건 개발자마다 취향이 탈 것 같네요. 해당 api를 구현한 사람이나 자주 봐서 익숙한 사람은 @RequestMapping()에 설정된 url을 알고 있어서 @post @get 매핑url만 봐도 전체 url을 알 수 있지만 처음 보는 사람은 @post, @get만 봐서는 헷갈려서 @RequestMapping의 url을 계속 찾아서 보는 경우도 있을 것 같아요.
그래서 저는 @post, @get에 명확하게 전체 url을 쓰는 방식을 선호합니다!

**Comment by yo0919** [comment]
> 이 방법도 좋은 방법이라고 생각합니다. 이건 개발자마다 취향이 탈 것 같네요. 해당 api를 구현한 사람이나 자주 봐서 익숙한 사람은 @RequestMapping()에 설정된 url을 알고 있어서 @post @get 매핑url만 봐도 전체 url을 알 수 있지만 처음 보는 사람은 @post, @get만 봐서는 헷갈려서 @RequestMapping의 url을 계속 찾아서 보는 경우도 있을 것 같아요. 그래서 저는 @post, @get에 명확하게 전체 url을 쓰는 방식을 선호합니다!

이것도 충분히 일리있는것같아요. 아무래도 협업하다보면 본인이 맡은 부분이 아니면 한눈에 들어오기 어렵기도 하니까요!
그럼 기존방법을 유지하도록 하겠습니다~
