### ISSUE TITLE
[BE] 외부api 호출을 백엔드에서 처리하는게 맞을까요?

### ISSUE THREAD

**Issue by yo0919** [softeerbootcamp-3rd/Team7-FiveGuys#69]
## ✏️ 논의하고 싶은 내용
> 외부api호출을 서버에서 하는게 맞을까요?
<br>

## 📝 찾아본 내용
- 현재 사용자의 출발/목적지에 따른 요금,시간,경로까지 서버에서 계산해서 보내주고있고, 또 최적의 경로를 계산하는로직과 한글로된 출발/목적지를 좌표로 변환하는 로직 또한 백엔드에서 처리하고 있습니다.
- 이과정에서 드는의문이 서버에서 외부 api를 호출하는동안 대략 0.7~1초의 시간이 발생하는데 이부분이 성능에 크게 영향을 미치지않는가 에대한 생각이 듭니다. ms단위의 시간을 줄이려고 쿼리최적화를 하는데 이부분에서 너무 많은 시간이 소요되는게 아닌가 싶은 생각도들구요
- 만약 이로직이 안드로이드에 들어가게된다면, 안드로이드에서 모든 계산을 하고 다음화면으로 넘어가는데에 걸리는 소요시간이 좀 걸려도 상관없지만 백엔드에 들어가면 전체사용자에게 영향을 미치게 될것같습니다.
- 또한 외부api를 호출하는도중 외부api자체가 터지면 우리 서버가 죽어버릴수도 있다는점도 고려해봐야 할것같습니다.(예외처리를 빡세게하면 해결될수도 있는 문제지만)
<br>

## 결론
> 외부api를 서버에서 호출해도 괜찮을까요? 
만약 안드로이드로 넘긴다면 안드로이드에서 구현이 가능할까요?
힘들것같다면 현실적인 문제로 백엔드에서 처리하고 그 이유를 정하면 좋을것같아요
<br>

**Comment by eyeben** [comment]
저도 안드로이드에서 처리를 하는게 전체적인 성능면에서는 더 좋을 거라고 생각합니다.
대신 서버측에서 유저의 위치를 실시간으로 알 수 없게 되는거처럼 모니터링을 할 수 없게 되는게 단점이네요.

**Comment by lsh2613** [comment]
먼저 3번에 대해 전체 사용자에게 영향을 미치게 될 것 같습니다.라는 부분이 약간 애매할 것 같네요.
단순히 해당 요청을 처리해야 해서 전체 사용자에게 영향을 준다고 생각하지는 않습니다. 클라이언트의 요청을 처리하기 위해서 서버에서도 여러 개의 스레드가 존재하고 각 스레드가 해당 요청들을 맡아 처리하기 때문에 다른 클라이언트의 요청에 영향을 가나?라는 질문에는 성능적인 측면에서는 '아니다'라고 생각합니다.

하지만 RestTemplate을 사용했던 걸로 보아 해당 템플릿은 동기방식으로 응답이 올 때까지 해당 스레드가 block되어 다른 요청이 들어왔을 때 가용 가능한 스레드가 존재할 확률이 줄어들어서 이 부분에서는 영향이 갈 수 있다. 라고 생각을 합니다.

결론적으로 3번의 내용에 대해서는 이 요청을 처리할 때 다른 스레드에게 영향을 주진 않지만 사용 가능한 스레드가 없어 이를 대기해야 하는 경우라면 영향을 줄 수 있다 라고 생각되네요.

**Comment by lsh2613** [comment]
4번에 의견이 정확히 이해가 가지 않습니다. 외부 api를 처리하는 서버가 터지면 해당 서버로 요청을 보내는 저희 측 서버도 같이 죽어버릴 수 있을까요??
만약 동기 방식으로 해당 요청에 대한 응답을 기다리는데 이 요청을 처리하는 서버가 터져서 응답을 받지 못해 우리 측 서버에 영향을 갈 수 있다 라는 의견이라면 이 요청에 대해 time-out을 설정하여 이 기간 동안 응답을 받지 못한다면 요청을 끊어버리는 방법으로 해결할 수 있을 것 같습니다!

**Comment by yo0919** [comment]
> 먼저 3번에 대해 전체 사용자에게 영향을 미치게 될 것 같습니다.라는 부분이 약간 애매할 것 같네요. 단순히 해당 요청을 처리해야 해서 전체 사용자에게 영향을 준다고 생각하지는 않습니다. 클라이언트의 요청을 처리하기 위해서 서버에서도 여러 개의 스레드가 존재하고 각 스레드가 해당 요청들을 맡아 처리하기 때문에 다른 클라이언트의 요청에 영향을 가나?라는 질문에는 성능적인 측면에서는 '아니다'라고 생각합니다.
> 
> 하지만 RestTemplate을 사용했던 걸로 보아 해당 템플릿은 동기방식으로 응답이 올 때까지 해당 스레드가 block되어 다른 요청이 들어왔을 때 가용 가능한 스레드가 존재할 확률이 줄어들어서 이 부분에서는 영향이 갈 수 있다. 라고 생각을 합니다.
> 
> 결론적으로 3번의 내용에 대해서는 이 요청을 처리할 때 다른 스레드에게 영향을 주진 않지만 사용 가능한 스레드가 없어 이를 대기해야 하는 경우라면 영향을 줄 수 있다 라고 생각되네요.

>4번에 의견이 정확히 이해가 가지 않습니다. 외부 api를 처리하는 서버가 터지면 해당 서버로 요청을 보내는 저희 측 서버도 같이 죽어버릴 수 있을까요??
만약 동기 방식으로 해당 요청에 대한 응답을 기다리는데 이 요청을 처리하는 서버가 터져서 응답을 받지 못해 우리 측 서버에 영향을 갈 수 있다 라는 의견이라면 이 요청에 대해 time-out을 설정하여 이 기간 동안 응답을 받지 못한다면 요청을 끊어버리는 방법으로 해결할 수 있을 것 같습니다!

- 말씀해주신 내용을 보니 무슨 말씀인지 알것같네요. 제가 생각했던것은 여러개의 쓰레드가 있을때에 여러명의 사용자가(예를들어 10개의 쓰레드와 100만명의 사용자) 이용할때, 하나의 쓰레드에서 외부 api를 호출하는데에 1초가량 시간을 소요한다면, 10만초가 걸리는게 아닌가? 라는 생각이 들었던건데, resttemplate이 아닌 webclient로 비동기적으로 동작하게 한다면 이부분은 어느정도 해결되는것 같긴합니다. 
- 4번또한 '서버가 죽는다'는 표현은 적절치 않은것같고, 네이버맵 서버가 터져서 모든 쓰레드가 요청을 받지 못해 timeout이 걸리는 상황이 되면 우리 서버가 정상작동이 어렵다는 말이 더 맞는것같습니다. 그렇기 때문에 외부 서버가 터져서 모든 쓰레드에서 timeout기간동안 아무동작도 하지 못하는게 걱정이 되었던것인데 webclient로 어느정도 해결이 가능하지 않을까? 싶긴합니다.

## 결론
백엔드에서 왜 구현하면 안되느냐 보다 백엔드에서 왜 구현해야하는가 에 대한 질문에 명확히 대답하기 힘든것같습니다..
- 만약 이부분에서 키값등의 보안이 중요하고, 외부 api호출하는 내용을 db에 저장하는 과정이 있다면 서버에서 처리하는것이 이점이 많고 또 보안이슈로 서버에서 처리해야만 할것같지만, 사용자가 이동하는 정보에 따라서 실시간으로 경로랑 다른값들이 변화할수있는 상황이라면, 서버를 거치지 않고 안드로이드에서 자체적으로 처리하는게 더 논리적으로 맞는것같다는 생각이드네요.. 
- 현재 서버의 api(현재는 operations/optimized-route)를 호출하는 과정을 (https://naveropenapi.apigw.ntruss.com/map-direction-15/v1/driving)를 호출해서 지금 백엔드에 있는 로직을 java에서 kotlin으로 변환해 원하는 메타데이터 값을 뽑아오면 되지않나싶습니다.

**Comment by lsh2613** [comment]
'예를들어 10개의 쓰레드와 100만명의 사용자) 이용할때, 하나의 쓰레드에서 외부 api를 호출하는데에 1초가량 시간을 소요한다면, 10만초가 걸리는게 아닌가?'라는 내용은 서버의 스레드가 하나 있을 경우에 대해서 계산이 된 것 같습니다. 제가 말씀 드린 건 비동기가 아니더라도 클라이언트의 요청을 처리하는 스레드가 서버에서도 여러 개 존재하기 때문에 block이 되지 않는 한 문제가 되지 않을 거라고 생각했습니다

**Comment by yo0919** [comment]
음.. '예를들어 10개의 쓰레드와 100만명의 사용자가 이용할때, 하나의 쓰레드에서 외부 api를 호출하는데에 1초가량 시간을 소요한다면, 10만초가 걸리는게 아닌가?' 라는 의문은 단순히 (사용자수/쓰레드수 * 1개의 쓰레드가 처리하는 시간) 만큼 시간이 소요되지 않는가? 라는 의문이었는데 찾아보면 찾아볼수록 이는 굉장히 단순하게 생각했을때이고, 실제 서버에서는 사용자 요청을 병렬로 처리할 수 있도록 설계되어 있기 때문에 그정도의 시간은 걸리지않을것같긴해요

그래서 제가 지금드는 생각은, 네이버맵api 호출과정은 프로젝트 핵심기능이기때문에 거의 모든 유저가 사용하게 될텐데 이과정을 resttemplate을 사용하게 된다면 쓰레드풀을 사용하더라도 모든 쓰레드가 거의 block이 되지않나 싶습니다. 
이부분은 webclient를 사용하고 관련 로직들도 비동기로 변환하는게 최선이지 않을까 싶어요

**Comment by lsh2613** [comment]
그러게요 저도 이 부분에 대해 공부할수록 동기vs비동기, 블로킹vs논블로킹에 대한 개념이 많이 약하다는 것을 느꼈고 같이 공부해보고 고민해보면 좋은 주제인 것 같아요 따로 이부분에 대해서 이야기 나눌 수 있는 이슈를 한 번 파보겠습니다
